# Generated by Django 3.0.8 on 2020-07-13 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_setup', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attempts_left',
            field=models.IntegerField(default=6, editable=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_word',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_value', models.CharField(max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_setup.Game')),
            ],
        ),
    ]
